import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import {
  AiFillStar,
  AiOutlineHeart,
  AiOutlineMinus,
  AiOutlinePlus,
  AiOutlineSearch,
} from 'react-icons/ai';
import { BiFoodTag } from 'react-icons/bi';
import useGetData from '../ReactQuery/useGetData';
import { BsArrowRight } from 'react-icons/bs';
import { useCartDetailsContext } from '../context/CartDetailsContext';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const { isLoading, isError, isFetching, data } = useGetData();
  const { cartData, setCartData } = useCartDetailsContext();

  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="sticky top-0 z-50 text-gray-300 bg-slate-900 px-28">
        <h3 className="text-4xl">McDonald&apos;s</h3>
        <div className=" text-gray-400 grid items-center justify-center  grid-cols-3 divide-x  w-[240px] h-8 my-2">
          <div className="flex items-center gap-2 text-center">
            <AiFillStar /> <span className="text-xs">4.3</span>
          </div>
          <div>
            <h6 className="ml-2 text-xs text-center">35 mins</h6>
          </div>
          <div>
            <h6 className="ml-2 text-xs text-center">
              &#8377; 400 for two
            </h6>
          </div>
        </div>
        <div className="flex items-center pb-4 gap-9 ">
          <div className="flex items-center h-12 px-1 rounded bg-zinc-100">
            <AiOutlineSearch
              color="black"
              size="18"
              className="ml-3"
            />
            <input
              type="text"
              placeholder="Search for dishes..."
              className="mr-2 text-gray-700 border-0 w-80 bg-zinc-100 focus:outline-none "
            />
          </div>
          <div className="flex items-center h-12 px-4 rounded bg-zinc-100">
            <input
              type="checkbox"
              className="mr-2 text-gray-700 bg-zinc-100 focus:outline-none "
            />
            <h6 className="text-gray-800">Veg Only</h6>
          </div>
          <div className="flex items-center h-12 gap-3 px-4 rounded bg-zinc-100">
            <AiOutlineHeart
              color="black"
              size="18"
              className="ml-3"
            />
            <h6 className="text-gray-800">Favorite</h6>
          </div>
        </div>
      </div>
      <div className="flex w-full h-full gap-4 px-28 ">
        <div className="w-9/12">
          {!isError &&
            !isLoading &&
            !isFetching &&
            data &&
            data.slice(0, 10).map((item: any, index: any) => (
              <div
                key={index}
                className="border-b-[3px] border-gray-300 flex items-center justify-between w-full py-8 "
              >
                <div className="flex flex-col w-8/12 gap-3">
                  <BiFoodTag color="green" size="22" />
                  <h4 className="text-3xl font-semibold text-gray-800">
                    {item.item_name}
                  </h4>
                  <h5 className=""> &#8377; {item.price}</h5>
                  <p className="">
                    Lorem ipsum dolor sit amet, consectetur
                    adipisicing elit. Eveniet laborum corrupti ea
                    temporibus quis sequi amet? .
                  </p>
                  <button
                    className="text-white bg-green-500 w-28 h-9"
                    onClick={() =>
                      setCartData([
                        ...cartData,
                        {
                          id: item.id,
                          qty: 1,
                          price: item.price,
                          name: item.item_name,
                        },
                      ])
                    }
                  >
                    Add To Cart
                  </button>
                </div>
                <div className="relative flex justify-end w-4/12">
                  <Image
                    src="/burger-trail-feat.jpg"
                    width={200}
                    height={200}
                    alt="burger-trail-feat"
                  />
                  <div className="absolute flex items-center h-10 gap-5 px-2 bg-white border border-gray-400 shadow right-14 bottom-1">
                    <button className="">
                      <AiOutlineMinus size="20" />
                    </button>
                    <h1 className="">1</h1>
                    <button className="">
                      <AiOutlinePlus size="20" />
                    </button>
                  </div>
                </div>
              </div>
            ))}
        </div>
        <div className="flex flex-col w-3/12 gap-2 mt-4">
          <h1 className="text-4xl font-bold">Cart</h1>
          <h5 className="text-sm font-semibold">
            {cartData.length > 0 && cartData.length} Items
          </h5>
          <div className="flex flex-col gap-2">
            {cartData.length > 0 &&
              cartData.map((item: any, index: any) => (
                <div key={index} className="flex items-center">
                  <div className="flex items-start w-1/12 h-full">
                    <BiFoodTag color="green" size="22" />
                  </div>
                  <div className="w-5/12">
                    <h2 className="text-xl font-semibold">
                      {item.name}
                    </h2>
                  </div>
                  <div className="w-3/12">
                    <div className="flex items-center w-24 h-10 gap-3 px-2 bg-white border border-gray-400 shadow">
                      <button className="">
                        <AiOutlineMinus size="20" />
                      </button>
                      <h1 className="">{item.qty}</h1>
                      <button className="">
                        <AiOutlinePlus size="20" />
                      </button>
                    </div>
                  </div>
                  <div className="w-2/12">
                    <h5 className=""> &#8377; {item.price}</h5>
                  </div>
                </div>
              ))}
          </div>
          <div className="flex justify-between mt-8">
            <div className="">
              <h5 className="text-sm font-bold">Subtotal</h5>
              <h6 className="text-xs ">Extra charges may apply</h6>
            </div>
            <h5 className="text-sm font-bold">
              &#8377;{' '}
              {cartData.length > 0 &&
                cartData.reduce(
                  (accumulator: any, current: any) =>
                    accumulator + current.price,
                  0
                )}
            </h5>
          </div>
          <button
            className="flex items-center justify-center gap-3 mt-2 text-xl text-white bg-green-600 h-14"
            onClick={() => router.push('checkoutPage')}
          >
            Checkout
            <BsArrowRight className="mt-1" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default Home;
